"use strict";

/**
 * The documentation site itself.
 *
 * Its chrome, navigation and search index are generated by build.py and its
 * behaviour lives in docs/assets/docs.js, so none of it is covered by the
 * component specs. These tests drive the built pages the way a reader does.
 */

const { test } = require("node:test");
const assert = require("node:assert/strict");
const { readFileSync, readdirSync } = require("node:fs");
const { join } = require("node:path");
const { useHarness } = require("./harness");

const ui = useHarness();
const ROOT = join(__dirname, "..");

const DOC_PAGES = readdirSync(join(ROOT, "docs"))
  .filter((name) => name.endsWith(".html"))
  .map((name) => "docs/" + name);

// --------------------------------------------------------------------------
// Generated chrome
// --------------------------------------------------------------------------

test("every docs page carries the same generated navigation", () => {
  // The sidebar used to be copy-pasted per page, and drifted: pages were
  // missing links to pages added after them. Generated from one table now,
  // so identical link sets are the invariant worth pinning.
  const linkSets = DOC_PAGES.map((page) => {
    const html = readFileSync(join(ROOT, page), "utf8");
    const nav = html.slice(html.indexOf("docs-sidebar"), html.indexOf("</aside>"));
    return {
      page,
      links: [...nav.matchAll(/href="([^"]+)"/g)].map((m) => m[1]).join(","),
    };
  });

  const expected = linkSets[0].links;
  assert.ok(expected.length > 0, "the sidebar should contain links");
  linkSets.forEach((entry) =>
    assert.equal(entry.links, expected, entry.page + " has a different sidebar")
  );
});

test("each page marks itself active and links to a real file", () => {
  const names = new Set(readdirSync(join(ROOT, "docs")));

  DOC_PAGES.forEach((page) => {
    const html = readFileSync(join(ROOT, page), "utf8");
    const active = [...html.matchAll(/docs-sidebar-link active" href="([^"]+)"/g)];
    assert.equal(active.length, 1, page + " must mark exactly one nav item active");
    assert.equal("docs/" + active[0][1], page, page + " marks the wrong item active");

    [...html.matchAll(/class="docs-sidebar-link[^"]*" href="([^"#]+)"/g)].forEach((m) => {
      const target = m[1].split("/").pop();
      assert.ok(names.has(target) || m[1].startsWith("examples/"),
        page + " links to a missing page: " + m[1]);
    });
  });
});

test("the search index covers every page and section", () => {
  const source = readFileSync(join(ROOT, "docs/assets/search-index.js"), "utf8");
  const index = JSON.parse(source.slice(source.indexOf("=") + 1, source.lastIndexOf(";")));

  assert.ok(index.length > 50, "expected a populated index, got " + index.length);

  DOC_PAGES.forEach((page) => {
    const name = page.replace("docs/", "");
    const html = readFileSync(join(ROOT, page), "utf8");
    const sections = [...html.matchAll(/<section class="docs-section" id="([^"]+)"/g)];

    sections.forEach(([, anchor]) => {
      const href = name + "#" + anchor;
      assert.ok(
        index.some((entry) => entry.href === href),
        "search index is missing " + href + " -- rerun build.py"
      );
    });
  });
});

// --------------------------------------------------------------------------
// Search palette
// --------------------------------------------------------------------------

test("Ctrl+K opens the palette, filters, and Escape closes it", async () => {
  await ui.visit("/docs/components.html", async (page) => {
    assert.equal(await page.count(".docs-palette"), 0, "built lazily, on first open");

    await page.press("k", ["ctrl"]);
    assert.equal(await page.isVisible(".docs-palette"), true);
    assert.equal(
      await page.evaluate(() => document.activeElement.className),
      "docs-palette-input",
      "the input should take focus so you can type immediately"
    );

    await page.type(".docs-palette-input", "multiselect");
    const hits = await page.evaluate(() =>
      [...document.querySelectorAll(".docs-palette-item")].map((a) => a.getAttribute("href"))
    );
    assert.ok(hits.length > 0, "expected a match for 'multiselect'");
    assert.ok(hits[0].indexOf("#multiselect") !== -1, "best match should be the section itself");

    await page.press("Escape");
    assert.equal(await page.isVisible(".docs-palette"), false);
    assert.equal(
      await page.evaluate(() => document.body.style.overflow),
      "",
      "closing must release the scroll lock"
    );
  });
});

test("the palette ranks a short exact heading above a long fuzzy match", async () => {
  await ui.visit("/docs/index.html", async (page) => {
    await page.press("k", ["ctrl"]);
    await page.type(".docs-palette-input", "drng");

    const titles = await page.evaluate(() =>
      [...document.querySelectorAll(".docs-palette-title")].map((el) => el.textContent)
    );
    assert.equal(titles[0], "Date range", "got: " + titles.slice(0, 3).join(" | "));
  });
});

test("arrow keys move the selection and Enter follows it", async () => {
  await ui.visit("/docs/components.html", async (page) => {
    await page.press("k", ["ctrl"]);
    await page.type(".docs-palette-input", "table");
    await page.press("ArrowDown");

    const target = await page.evaluate(() =>
      document.querySelector(".docs-palette-item.active").getAttribute("href")
    );
    assert.ok(target, "something should be selected");

    await page.press("Enter");
    await page.waitFor(() => window.location.hash !== "" || null);
    assert.ok(
      (await page.evaluate(() => window.location.href)).indexOf(target.split("#").pop()) !== -1,
      "Enter should navigate to the highlighted result"
    );
  });
});

// --------------------------------------------------------------------------
// Code blocks
// --------------------------------------------------------------------------

test("code blocks are highlighted without corrupting the text", async () => {
  await ui.visit("/docs/getting-started.html", async (page) => {
    const result = await page.evaluate(() => {
      const blocks = [...document.querySelectorAll("pre.ui-code-block > code")];
      return {
        total: blocks.length,
        tokenised: blocks.filter((c) => c.querySelector("span[class^=tok-]")).length,
        // The copy button reads textContent, so highlighting must be
        // invisible to it -- no stray markup, no lost characters.
        text: blocks[0].textContent,
        languages: blocks.map((c) => (c.className.match(/docs-lang-(\w+)/) || [])[1]),
      };
    });

    assert.ok(result.total > 0);
    assert.equal(result.tokenised, result.total, "every block should be tokenised");
    assert.ok(result.text.indexOf("<link rel=\"stylesheet\"") !== -1,
      "textContent must survive highlighting verbatim");
    assert.ok(result.text.indexOf("&lt;") === -1, "and must not contain escaped entities");
    assert.ok(result.languages.indexOf("css") !== -1, "a bare @rule should read as CSS");
  });
});

test("a hex colour is highlighted whole, not split", async () => {
  // The number rule used to bite "143b" out of #143b6b and leave the rest a
  // different colour.
  await ui.visit("/docs/getting-started.html", async (page) => {
    const split = await page.evaluate(() =>
      [...document.querySelectorAll("pre.ui-code-block .tok-number")]
        .map((s) => s.textContent)
        .filter((t) => /^[0-9a-f]{3,}$/i.test(t) && t.indexOf("#") === -1)
    );
    assert.deepEqual(split, [], "hex colours must be matched before plain numbers");
  });
});

test("framework tabs switch the sample and every block follows", async () => {
  await ui.visit("/docs/components.html", async (page) => {
    const tabs = await page.count("#multiselect [data-docs-framework]");
    assert.equal(tabs, 3, "expected HTML / Angular / React");

    await page.click('#multiselect [data-docs-framework="angular"]');

    const state = await page.evaluate(() => {
      const wrap = document.querySelector("#multiselect .docs-code-wrap");
      return {
        text: wrap.querySelector("code").textContent,
        active: wrap.querySelector(".ui-tab.ui-active").dataset.docsFramework,
        stored: localStorage.getItem("docs-framework"),
        everyBlock: [...document.querySelectorAll(".docs-code-wrap[data-docs-tabbed]")]
          .map((w) => w.querySelector(".ui-tab.ui-active").dataset.docsFramework),
      };
    });

    assert.equal(state.active, "angular");
    assert.ok(state.text.indexOf("formControlName") !== -1, "should show the Angular sample");
    assert.ok(state.text.indexOf("&lt;") === -1, "template entities must be decoded");
    assert.equal(state.stored, "angular", "the choice should persist");
    assert.deepEqual(
      [...new Set(state.everyBlock)],
      ["angular"],
      "one language is chosen site-wide, not per block"
    );
  });
});

// --------------------------------------------------------------------------
// Navigation
// --------------------------------------------------------------------------

test("headings get anchors and the on-this-page rail tracks scrolling", async () => {
  await ui.visit("/docs/utilities.html", async (page) => {
    const sections = await page.count(".docs-section[id]");
    assert.equal(await page.count(".docs-anchor"), sections, "one anchor per section");
    assert.equal(await page.count(".docs-toc-link"), sections, "one rail entry per section");

    await page.evaluate(() => {
      document.querySelector(".docs-section[id]:last-of-type").scrollIntoView();
    });
    await page.waitFor(() => document.querySelector(".docs-toc-link.active") || null);

    const active = await page.evaluate(() =>
      document.querySelector(".docs-toc-link.active").getAttribute("href")
    );
    assert.ok(active.startsWith("#"), "scroll spy should mark a rail entry active");
  });
});

test("the viewport toggle narrows a demo without disturbing its content", async () => {
  await ui.visit("/docs/components.html", async (page) => {
    const demo = "#navigation .docs-demo[data-docs-viewport]";
    assert.equal(await page.count(demo + " [data-docs-width]"), 3);

    const wide = await page.evaluate((sel) =>
      document.querySelector(sel + " .docs-viewport-stage").getBoundingClientRect().width,
      demo
    );

    await page.click(demo + ' [data-docs-width="mobile"]');
    const narrow = await page.evaluate((sel) =>
      document.querySelector(sel + " .docs-viewport-stage").getBoundingClientRect().width,
      demo
    );

    assert.ok(narrow < wide, "mobile should be narrower (" + narrow + " vs " + wide + ")");
    assert.ok(narrow > 300 && narrow < 420, "and roughly phone width, got " + narrow);

    // Rehoming the demo into a stage must not drop anything it contained.
    assert.ok(
      await page.evaluate((sel) =>
        document.querySelector(sel + " .docs-viewport-stage").children.length > 0, demo),
      "the demo's own markup should survive being wrapped"
    );
  });
});

test("active navigation states stay readable in both themes", async () => {
  // The framework's dark theme does not lighten --ui-primary, so using it
  // directly for active-item text put #2563eb on a near-black surface at
  // 2.7:1. The docs use --docs-accent for text-on-soft instead.
  await ui.visit("/docs/components.html", async (page) => {
    const ratios = await page.evaluate(() => {
      const ch = (c) => { const s = c / 255; return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4); };
      const lum = ([r, g, b]) => 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b);
      const parse = (v) => v.match(/[\d.]+/g).map(Number);
      const over = (fg, bg) => { const a = fg.length > 3 ? fg[3] : 1; return [0, 1, 2].map((i) => fg[i] * a + bg[i] * (1 - a)); };

      const measure = () => {
        const pageBg = parse(getComputedStyle(document.body).backgroundColor);
        return [".docs-sidebar-link.active", ".docs-kicker"].map((sel) => {
          const el = document.querySelector(sel);
          const st = getComputedStyle(el);
          const bg = over(parse(st.backgroundColor), pageBg);
          const fg = over(parse(st.color), bg);
          const l = [lum(fg), lum(bg)];
          return { sel, ratio: (Math.max(...l) + 0.05) / (Math.min(...l) + 0.05) };
        });
      };

      const root = document.documentElement;
      root.setAttribute("data-ui-theme", "light");
      const light = measure();
      root.setAttribute("data-ui-theme", "dark");
      const dark = measure();
      root.setAttribute("data-ui-theme", "light");
      return { light, dark };
    });

    [].concat(ratios.light, ratios.dark).forEach((entry) =>
      assert.ok(entry.ratio >= 4.5,
        entry.sel + " is " + entry.ratio.toFixed(2) + ":1, below AA 4.5:1")
    );
  });
});

test("the pager links to the neighbouring pages in order", async () => {
  await ui.visit("/docs/layout.html", async (page) => {
    const links = await page.evaluate(() =>
      [...document.querySelectorAll(".docs-pager-link")].map((a) => a.getAttribute("href"))
    );
    assert.deepEqual(links, ["getting-started.html", "components.html"]);
  });
});
